FROM python:3.8.8-slim-buster

LABEL maintainer="João Pedro Pinheiro <joaopedro.pinheiro88@gmail.com>"

RUN pip install --no-cache-dir --upgrade pip \
 && pip install Flask==1.1.2                 \
                peewee==3.14.2
